use_frameworks!

platform :ios, '8.0'

target 'OWWaterFallLayout_Example' do
  pod 'OWWaterFallLayout', :path => '../'

  target 'OWWaterFallLayout_Tests' do
    inherit! :search_paths

    
  end
end
